---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.name }}-{{ .Chart.AppVersion }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.backend.labels.name }}
    app.kubernetes.io/component: {{ .Values.backend.labels.component }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.backend.labels.name }}
      app.kubernetes.io/component: {{ .Values.backend.labels.component }}
  replicas: {{ .Values.backend.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.backend.labels.name }}
        app.kubernetes.io/component: {{ .Values.backend.labels.component }}
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:e2e
        ports:
        - name: redis-server
          containerPort: {{ .Values.backend.port }}