name: Infralovers Container Build

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    uses: infralovers/.github/.github/workflows/container.yml@main
    secrets:
      QUAY_USER: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_QUAY_ROBOT_ACCOUNT).username }}"
      QUAY_TOKEN: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_QUAY_ROBOT_ACCOUNT).password }}"
      BOT_ACCESS_TOKEN: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_GITHUB_INFRALOVERS).PAT }}"
      MONDOO_SERVICE_ACCOUNT: "${{ secrets.MONDOO_SERVICE_ACCOUNT }}"
    with:
      dockerfile: Dockerfile
      score: 50
      platforms: "linux/amd64, linux/arm64"
      release: true
      